version: "3.9"

services:
    db:
        hostname: db
        image: postgres:15
        container_name: myfridge-db
        environment:
            - POSTGRES_DB=myfridge
            - POSTGRES_USER=myfridge
            - POSTGRES_PASSWORD=myfridge123
        ports:
            - "5432:5432"
    web:
        hostname: web
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: myfridge-web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app/
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - celery
        env_file:
            - .env

    nginx:
        image: nginx:latest
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - web

    redis:
        image: redis:latest
        container_name: myfridge-redis
        ports:
            - "6379:6379"
    celery:
        build: .
        container_name: myfridge-celery
        command: celery -A myfridge.celery worker -l info
        volumes:
            - .:/app/
        depends_on:
            - db
            - redis