version: "3.9"

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=myfridge
            - POSTGRES_USER=myfridge
            - POSTGRES_PASSWORD=myfridge123
        ports:
            - "5432:5432"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app/
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - celery
    redis:
        image: redis
        ports:
            - "6379:6379"
    celery:
        build: .
        command: celery -A myfridge.celery worker -l info
        volumes:
            - .:/app/
        depends_on:
            - db
            - redis