# Generated by Django 4.2.1 on 2023-07-23 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dishes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="dishes.dish",
            ),
        ),
        migrations.AddField(
            model_name="favouritedish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dishes.dish"
            ),
        ),
        migrations.AddField(
            model_name="favouritedish",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favouritedish",
            unique_together={("user", "dish")},
        ),
    ]
