# Generated by Django 4.2.1 on 2023-07-23 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dishes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdailystatistics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mealdailyplan",
            name="breakfast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakfast",
                to="tools.meal",
            ),
        ),
        migrations.AddField(
            model_name="mealdailyplan",
            name="dinner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dinner",
                to="tools.meal",
            ),
        ),
        migrations.AddField(
            model_name="mealdailyplan",
            name="lunch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lunch",
                to="tools.meal",
            ),
        ),
        migrations.AddField(
            model_name="mealdailyplan",
            name="second_breakfast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_breakfact",
                to="tools.meal",
            ),
        ),
        migrations.AddField(
            model_name="mealdailyplan",
            name="tea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tea",
                to="tools.meal",
            ),
        ),
        migrations.AddField(
            model_name="mealdailyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="dish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dishes.dish",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
