# Generated by Django 4.2.1 on 2023-07-23 21:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "DifficultyLevel",
                "verbose_name_plural": "DifficultyLevels",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="images"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_edited", models.DateTimeField(auto_now=True)),
                ("kcal", models.IntegerField(blank=True, null=True)),
                ("gluten", models.BooleanField(default=False)),
                ("lactose", models.BooleanField(default=False)),
                ("meat", models.BooleanField(default=False)),
                ("vegetarian", models.BooleanField(default=False)),
                ("vegan", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="DishCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "DishCategory",
                "verbose_name_plural": "DishCategories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TimeToMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
            options={
                "verbose_name": "TimeToMake",
                "verbose_name_plural": "TimeToMake",
                "ordering": ("value",),
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OtherIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.type"
                    ),
                ),
            ],
            options={
                "verbose_name": "OtherIngredient",
                "verbose_name_plural": "OtherIngredients",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MainIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.type"
                    ),
                ),
            ],
            options={
                "verbose_name": "MainIngredient",
                "verbose_name_plural": "MainIngredients",
                "ordering": ("name",),
            },
        ),
    ]
